# Site settings
title: Juegos de Mesa
email:
description: > # this means to ignore newlines until "baseurl:"
  Informacion sobre el eventos de Juegos de Mesa para la Semana de la Juventud en Almendralejo 2023.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username: raultm
github_username: raultm
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown